config/routes.rb
Cats99::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :age, numericality: true, presence: true
  validates :birth_date, :name, presence: true
  validates :color, inclusion: %w(red blue black tan white green plaid), presence: true
  # validates :name, presence: true
  validates :sex, inclusion: %w(M F), presence: true
  
  has_many(:cat_rental_requests, dependent: :destroy)
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  belongs_to(:cat)
  validates :cat_id, :status, :start_date, :end_date, presence: true
  validates :status, inclusion: %w(APPROVED PENDING DENIED)
  validate :approval_conflict?
  
  def after_initialize
    self.status ||= 'PENDING'
  end
  
  def overlapping_requests
    conflicts = CatRentalRequest
      .where("cat_id = ?", self.cat_id)
      .where("(? BETWEEN start_date AND end_date) OR 
              (? BETWEEN start_date AND end_date) OR
              (start_date BETWEEN ? AND ?) OR 
              (end_date BETWEEN ? AND ?)",
              self.start_date, self.end_date,
              self.start_date, self.end_date,
              self.start_date, self.end_date 
              )
    conflicts = conflicts.where("id <> ?", self.id) unless self.id.nil?
    conflicts
  end
  
  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end
  
  def approval_conflict?
    return false if overlapping_approved_requests.empty? || self.status != 'APPROVED'
    errors[:cat_id] << "already rented for that time frame"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @request = CatRentalRequest.new
    render :new
  end
  
  def create
    @request = CatRentalRequest.new(cat_rental_request_params)
    @cat = Cat.find(@request.cat_id)
    
    if @request.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end
  
  
  private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :status, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
      
  end
  
  def index
    @cats = Cat.all
  end
  
  def show
    @cat = Cat.find(params[:id])
  end
  
  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end
  
  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end
  
  def new
    @cat = Cat.new
    render :new
  end
  
  private
  
  def cat_params
    cat_attrs = [:name, :age, :sex, :description, :color, :birth_date]
    params.require(:cat).permit(*cat_attrs)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<h3> CAT RENTER </h3>

<form action = "<%= cat_rental_requests_url %>" method = "POST" >

<p>
<label for = 'cat_rental_request'>Start Date</label>
<input name = "cat_rental_request[start_date]" id = "cat_rental_request_start_date" type = "date" value = "<%= @request.start_date%>">
</p>

<p>
<label for = 'cat_rental_request'>End Date</label>
<input name = "cat_rental_request[end_date]" id = "cat_rental_request_end_date" type = "date" value = "<%= @request.end_date%>">
</p>

<p>
<label for = 'cat_rental_request_cat_id'>Cat Name</label>
<select name="cat_rental_request[cat_id]">
<option></option>
<% Cat.all.each do |cat|%>
<option value = "<%= cat.id %>"
  <% if @request.cat_id == cat.id %>selected="selected"<% end %>>
  <%= cat.name %> 
</option>
<% end %>
</select>
</p>

<input type="submit" value="Request a cat">

app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
<% form_method = cat.persisted? ? "PATCH" : "POST" %>
<% submit_text = cat.persisted? ? "Update" : "Create" %>

<form action = "<%= action_url %>" method = "post" >
<input type="hidden" name="_method" value= "<%= form_method %>">

<p>
<label for = 'cat_name'>Name</label>
<input name = "cat[name]" id = "cat_name" type = "text" value = "<%= @cat.name %>">
</p>

<p>
<label for = 'cat_age'>Age</label>
<input name = "cat[age]" id = "cat_age" type = "number" value = "<%= @cat.age%>">
</p>


<p>
<label for = 'cat_birth_date'>Birthdate</label>
<input name = "cat[birth_date]" id = "cat_birth_date" type = "date" value = "<%= @cat.birth_date%>">
</p>


<p>
<label for = 'cat_color'>Color</label>
<select name="cat[color]">
<option></option>
<% %w(red blue black tan white green plaid).each do |color|%>
<option value = "<%= color %>"
  <% if @cat.color == color%>selected="selected"<% end%>>
  <%= color%> 
</option>
<% end %>
</select>
</p>


<p>
Sex
<div>
<input name = "cat[sex]" id = "cat_sex" type = "radio" value="M"
  <% if @cat.sex == 'M'%>checked="checked"<% end%>>
<label for="cat_sex_m">Male</label>
<input name="cat[sex]" id = "cat_sex" type="radio" value="F"
  <% if @cat.sex == 'F'%>checked="checked"<% end%>>
<label for="cat_sex_f">Female</label>
</div>                                 
</p>

<p>
<label for = 'cat_description'>Description</label>
<textarea name = "cat[description]" id = "cat_description">
<%= @cat.description%>
</textarea>
</p>


<input type="submit" value="<%= submit_text %>">

app/views/cats/edit.html.erb
<h3>Edit</h3>
<%= render "form", cat: @cat%>

app/views/cats/index.html.erb
<h1>All of the cats</h1>

<table>
  <% @cats.each do |cat|%>
    <tr>
      <td><%= link_to "#{cat.name.capitalize}", cat_url(cat.id) %></td>
    </tr>
  <% end %>
  <tr>
    <td><%= link_to "New Cat", new_cat_url%></td>
  </tr>
</table>

app/views/cats/new.html.erb
<h3> CATSTUCTOR </h3>

<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<h1><%= @cat.name.capitalize %></h1>

<table>
    <tr>
      <td>Name:</td>
      <td><%= @cat.name.capitalize %></td>
    </tr>
    <tr>
      <td>Age:</td>
      <td><%= @cat.age %></td>
    </tr>
    <tr>
      <td>Birthday:</td>
      <td><%= @cat.birth_date %></td>
    </tr>
    <tr>
      <td>Color:</td>
      <td><%= @cat.color.capitalize %></td>
    </tr>
    <tr>
      <td>Sex:</td>
      <td><%= @cat.sex.capitalize %></td>
    </tr>
    <tr>
      <td>Description:</td>
      <td><%= @cat.description %></td>
    </tr>
    <tr><td>Requests</td>
      <td>
        <% sorted_requests = @cat.cat_rental_requests.sort_by{|r| r.start_date}%>
        <% sorted_requests.each do |request|%>
          Start:  <%= request.start_date %>
          End:    <%= request.end_date%>
          Status: <%= request.status %>
          <br>
        <% end %>
      </td>
    </tr>
  
    
    
</table>

<p><%= link_to "This cat needs improvement", edit_cat_url%></p>
</p><%= link_to "I'm bored with this cat", cats_url%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>